name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Validar sintaxis de la app
      run: |
        cd app
        node --check index.js

    - name: Validar Docker Compose
      run: docker compose config

    - name: Desplegar contenedores
      run: docker compose up -d --build
